version: "3.9"

services:
  presto-coordinator:
    image: prestodb/presto:latest
    container_name: presto-coordinator
    hostname: presto-coordinator
    ports:
      - "8080:8080"   # Expose Presto UI and CLI access
    volumes:
      - ./coordinator/config.properties:/opt/presto-server/etc/config.properties
      - ./coordinator/node.properties:/opt/presto-server/etc/node.properties
      - ./coordinator/jvm.config:/opt/presto-server/etc/jvm.config
      - ./coordinator/catalog:/opt/presto-server/etc/catalog
      - ./insert-postgres.sql:/opt/presto-server/etc/insert-postgres.sql
      - ./insert-mongo.sql:/opt/presto-server/etc/insert-mongo.sql
      - ./insert-cassandra.sql:/opt/presto-server/etc/insert-cassandra.sql
    # depends_on:
    #   cassandra:
    #     condition: service_healthy

  worker1:
    image: prestodb/presto:latest
    container_name: worker1
    hostname: worker1
    volumes:
      - ./worker1/config.properties:/opt/presto-server/etc/config.properties
      - ./worker1/node.properties:/opt/presto-server/etc/node.properties
      - ./worker1/jvm.config:/opt/presto-server/etc/jvm.config
      - ./coordinator/catalog:/opt/presto-server/etc/catalog
    depends_on:
      - presto-coordinator

  worker2:
    image: prestodb/presto:latest
    container_name: worker2
    hostname: worker2
    volumes:
      - ./worker2/config.properties:/opt/presto-server/etc/config.properties
      - ./worker2/node.properties:/opt/presto-server/etc/node.properties
      - ./worker2/jvm.config:/opt/presto-server/etc/jvm.config
      - ./coordinator/catalog:/opt/presto-server/etc/catalog
    depends_on:
      - presto-coordinator

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: presto
      POSTGRES_DB: presto

  mongodb:
    image: mongo
    command: ["--wiredTigerCacheSizeGB", "1"]
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # cassandra:
  #   image: cassandra
  #   container_name: cassandra
  #   ports:
  #     - "9042:9042"
  #   volumes:
  #     - "cassandra-data:/var/lib/cassandra"
  #   environment:
  #     CASSANDRA_USER: admin
  #     CASSANDRA_PASSWORD: admin
  #   healthcheck:
  #     test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES' || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 20

volumes:
  postgresql-data:
  mongo_data:
  # cassandra-data: