version: '3.9'

services:
  coordinator:
    image: prestodb/presto:latest
    container_name: coordinator
    ports:
      - "8080:8080"
    volumes:
      - ./coordinator/config.properties:/opt/presto-server/etc/config.properties
      - ./coordinator/node.properties:/opt/presto-server/etc/node.properties
      - ./coordinator/jvm.config:/opt/presto-server/etc/jvm.config
      - ./catalog:/opt/presto-server/etc/catalog
  
  worker1:
    image: prestodb/presto:latest
    container_name: worker1
    ports:
      - "8081:8081"
    depends_on:
      - coordinator
    volumes:
      - ./worker1/config.properties:/opt/presto-server/etc/config.properties
      - ./worker1/node.properties:/opt/presto-server/etc/node.properties
      - ./worker1/jvm.config:/opt/presto-server/etc/jvm.config
      - ./catalog:/opt/presto-server/etc/catalog

  worker2:
    image: prestodb/presto:latest
    container_name: worker2
    ports:
      - "8082:8082"
    depends_on:
      - coordinator
    volumes:
      - ./worker2/config.properties:/opt/presto-server/etc/config.properties
      - ./worker2/node.properties:/opt/presto-server/etc/node.properties
      - ./worker2/jvm.config:/opt/presto-server/etc/jvm.config
      - ./catalog:/opt/presto-server/etc/catalog

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra

volumes:
  mongo-data:
  cassandra-data:
  postgres-data: